name: Zen Browser

on:
  workflow_dispatch
  
jobs:
  update-cask:
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4
    
    - name: Get version
      id: get_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: zen-browser
        repo: desktop
        excludes: prerelease, draft
        
    - name: Download ARM artifact
      id: download_artifact_arm
      uses: robinraju/release-downloader@v1
      with:
        repository: 'zen-browser/desktop'
        latest: true
        fileName: 'zen.macos-aarch64.dmg'
        
    - name: Download Intel artifact
      id: download_artifact_intel
      uses: robinraju/release-downloader@v1
      with:
        repository: 'zen-browser/desktop'
        latest: true
        fileName: 'zen.macos-x64.dmg'

    - name: Calculate ARM SHA-256
      id: sha256_arm
      run: |
        sha256=$(shasum -a 256 zen.macos-aarch64.dmg | awk '{print $1}')
        echo "sha256=$sha256" >> $GITHUB_OUTPUT

    - name: Calculate Intel SHA-256
      id: sha256_intel
      run: |
        sha256=$(shasum -a 256 zen.macos-x64.dmg | awk '{print $1}')
        echo "sha256=$sha256" >> $GITHUB_OUTPUT
        
    - name: Update Cask Formula
      run: |
        sed -i '' "s/version \".*\"/version \"${{ steps.get_version.outputs.release }}\"/" Casks/zen-browser.rb && \
          sed -i '' "s/sha256 arm:   \".*\"/sha256 arm:   \"${{ steps.sha256_arm.outputs.sha256 }}\"/" Casks/zen-browser.rb
          sed -i '' "s/sha256 intel:   \".*\"/sha256 intel:   \"${{ steps.sha256_intel.outputs.sha256 }}\"/" Casks/zen-browser.rb
    
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_options: '--no-verify --signoff'
        file_pattern: 'Casks/zen-browser.rb'
        repository: Casks
        status_options: '--untracked-files=no'
        add_options: '-u'
        push_options: '--force'
        skip_dirty_check: true    
        skip_fetch: true    
        skip_checkout: true
        disable_globbing: true

