# This is a basic workflow that is manually triggered

name: Zen Browser

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Update zen-browser cask'
        required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-cask:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get version
      id: get_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: zen-browser
        repo: desktop
        excludes: prerelease, draft
        
    - name: Download ARM artifact
      id: download_artifact_arm
      uses: dawidd6/action-download-artifact@v6
      with:
        repo: zen-browser/desktop
        name: zen.macos-aarch64.dmg

    - name: Download Intel artifact
      id: download_artifact_intel
      uses: dawidd6/action-download-artifact@v6
      with:
        repo: zen-browser/desktop
        name: zen.macos-x64.dmg

    - name: Calculate ARM SHA-256
      id: sha256_arm
      run: |
        sha256=$(shasum -a 256 ${{ steps.download_artifact_arm.outputs.download-path }} | awk '{print $1}')
        echo "sha256=$sha256" >> $GITHUB_OUTPUT

    - name: Calculate Intel SHA-256
      id: sha256_intel
      run: |
        sha256=$(shasum -a 256 ${{ steps.download_artifact_intel.outputs.download-path }} | awk '{print $1}')
        echo "sha256=$sha256" >> $GITHUB_OUTPUT
        
    - name: Update Cask Formula
      run: |
        sed -i '' "s/version \".*\"/version \"${{ steps.get_version.outputs.release }}\"/" Casks/zen-browser.rb && \
          sed -i '' "s/sha256 arm:   \".*\"/sha256 arm:   \"${{ steps.sha256_arm.outputs.sha256 }}\"/" Casks/zen-browser.rb
          sed -i '' "s/sha256 intel:   \".*\"/sha256 intel:   \"${{ steps.sha256_intel.outputs.sha256 }}\"/" Casks/zen-browser.rb
    
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_options: '--no-verify --signoff'
        file_pattern: 'Casks/zen-browser.rb'
        repository: Casks
        status_options: '--untracked-files=no'
        add_options: '-u'
        push_options: '--force'
        skip_dirty_check: true    
        skip_fetch: true    
        skip_checkout: true
        disable_globbing: true

